// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createAuditLog = `-- name: CreateAuditLog :one

INSERT INTO authentication_events
(
    id,
    event_type,
    user_id,
    email,
    ip_address,
    user_agent,
    success,
    failure_reason,
    metadata
)
VALUES
(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, event_type, user_id, email, ip_address, user_agent, success, failure_reason, metadata, created_at
`

type CreateAuditLogParams struct {
	ID            uuid.UUID `json:"id"`
	EventType     string    `json:"event_type"`
	UserID        uuid.UUID `json:"user_id"`
	Email         string    `json:"email"`
	IpAddress     string    `json:"ip_address"`
	UserAgent     string    `json:"user_agent"`
	Success       bool      `json:"success"`
	FailureReason string    `json:"failure_reason"`
	Metadata      []byte    `json:"metadata"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuthenticationEvent, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ID,
		arg.EventType,
		arg.UserID,
		arg.Email,
		arg.IpAddress,
		arg.UserAgent,
		arg.Success,
		arg.FailureReason,
		arg.Metadata,
	)
	var i AuthenticationEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.UserID,
		&i.Email,
		&i.IpAddress,
		&i.UserAgent,
		&i.Success,
		&i.FailureReason,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
