// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthenticationEvent = `-- name: CreateAuthenticationEvent :one


INSERT INTO authentication_events
(
    id,

    type,

    user_id,

    email,

    ip_address,

    user_agent,

    success,

    reason,

    metadata
)

VALUES
(
    $1,

    $2,

    $3,

    $4,

    $5,

    $6,

    $7,

    $8,

    $9
)

RETURNING id, type, user_id, email, ip_address, user_agent, success, reason, metadata, created_at
`

type CreateAuthenticationEventParams struct {
	ID        uuid.UUID   `json:"id"`
	Type      string      `json:"type"`
	UserID    *uuid.UUID  `json:"user_id"`
	Email     *string     `json:"email"`
	IpAddress *netip.Addr `json:"ip_address"`
	UserAgent pgtype.Text `json:"user_agent"`
	Success   bool        `json:"success"`
	Reason    *string     `json:"reason"`
	Metadata  []byte      `json:"metadata"`
}

// =====================================================
// Create Authentication Event
// =====================================================
func (q *Queries) CreateAuthenticationEvent(ctx context.Context, arg CreateAuthenticationEventParams) (AuthenticationEvent, error) {
	row := q.db.QueryRow(ctx, createAuthenticationEvent,
		arg.ID,
		arg.Type,
		arg.UserID,
		arg.Email,
		arg.IpAddress,
		arg.UserAgent,
		arg.Success,
		arg.Reason,
		arg.Metadata,
	)
	var i AuthenticationEvent
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.UserID,
		&i.Email,
		&i.IpAddress,
		&i.UserAgent,
		&i.Success,
		&i.Reason,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
