// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DeviceType string

const (
	DeviceTypeWEB     DeviceType = "WEB"
	DeviceTypeIOS     DeviceType = "IOS"
	DeviceTypeANDROID DeviceType = "ANDROID"
	DeviceTypeDESKTOP DeviceType = "DESKTOP"
	DeviceTypeSERVICE DeviceType = "SERVICE"
)

func (e *DeviceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeviceType(s)
	case string:
		*e = DeviceType(s)
	default:
		return fmt.Errorf("unsupported scan type for DeviceType: %T", src)
	}
	return nil
}

type NullDeviceType struct {
	DeviceType DeviceType `json:"device_type"`
	Valid      bool       `json:"valid"` // Valid is true if DeviceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeviceType) Scan(value interface{}) error {
	if value == nil {
		ns.DeviceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeviceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeviceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeviceType), nil
}

type RefreshTokenRevokeReason string

const (
	RefreshTokenRevokeReasonLOGOUT         RefreshTokenRevokeReason = "LOGOUT"
	RefreshTokenRevokeReasonREPLAYDETECTED RefreshTokenRevokeReason = "REPLAY_DETECTED"
	RefreshTokenRevokeReasonSECURITYPOLICY RefreshTokenRevokeReason = "SECURITY_POLICY"
	RefreshTokenRevokeReasonEXPIRED        RefreshTokenRevokeReason = "EXPIRED"
)

func (e *RefreshTokenRevokeReason) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RefreshTokenRevokeReason(s)
	case string:
		*e = RefreshTokenRevokeReason(s)
	default:
		return fmt.Errorf("unsupported scan type for RefreshTokenRevokeReason: %T", src)
	}
	return nil
}

type NullRefreshTokenRevokeReason struct {
	RefreshTokenRevokeReason RefreshTokenRevokeReason `json:"refresh_token_revoke_reason"`
	Valid                    bool                     `json:"valid"` // Valid is true if RefreshTokenRevokeReason is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRefreshTokenRevokeReason) Scan(value interface{}) error {
	if value == nil {
		ns.RefreshTokenRevokeReason, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RefreshTokenRevokeReason.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRefreshTokenRevokeReason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RefreshTokenRevokeReason), nil
}

type UserStatus string

const (
	UserStatusPENDING   UserStatus = "PENDING"
	UserStatusACTIVE    UserStatus = "ACTIVE"
	UserStatusSUSPENDED UserStatus = "SUSPENDED"
	UserStatusLOCKED    UserStatus = "LOCKED"
	UserStatusDELETED   UserStatus = "DELETED"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type AuthenticationEvent struct {
	ID        uuid.UUID          `json:"id"`
	Type      string             `json:"type"`
	UserID    *uuid.UUID         `json:"user_id"`
	Email     *string            `json:"email"`
	IpAddress *netip.Addr        `json:"ip_address"`
	UserAgent pgtype.Text        `json:"user_agent"`
	Success   bool               `json:"success"`
	Reason    *string            `json:"reason"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	SessionID *uuid.UUID         `json:"session_id"`
}

type EmailVerificationToken struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type OauthIdentity struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	Provider       string             `json:"provider"`
	ProviderUserID string             `json:"provider_user_id"`
	Email          string             `json:"email"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID            uuid.UUID                    `json:"id"`
	SessionID     uuid.UUID                    `json:"session_id"`
	FamilyID      uuid.UUID                    `json:"family_id"`
	ParentTokenID *uuid.UUID                   `json:"parent_token_id"`
	TokenHash     string                       `json:"token_hash"`
	ExpiresAt     pgtype.Timestamptz           `json:"expires_at"`
	ConsumedAt    pgtype.Timestamptz           `json:"consumed_at"`
	RevokedAt     pgtype.Timestamptz           `json:"revoked_at"`
	RevokedReason NullRefreshTokenRevokeReason `json:"revoked_reason"`
	CreatedAt     pgtype.Timestamptz           `json:"created_at"`
}

type Session struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	DeviceID        string             `json:"device_id"`
	DeviceName      *string            `json:"device_name"`
	DeviceType      DeviceType         `json:"device_type"`
	UserAgent       pgtype.Text        `json:"user_agent"`
	IpAddress       *netip.Addr        `json:"ip_address"`
	LastUsedAt      pgtype.Timestamptz `json:"last_used_at"`
	LastRefreshedAt pgtype.Timestamptz `json:"last_refreshed_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	RevokedReason   *string            `json:"revoked_reason"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID              uuid.UUID   `json:"id"`
	Email           string      `json:"email"`
	PasswordHash    pgtype.Text `json:"password_hash"`
	Status          UserStatus  `json:"status"`
	EmailVerifiedAt *time.Time  `json:"email_verified_at"`
	LastLoginAt     *time.Time  `json:"last_login_at"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
}
