// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_identity.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createOAuthIdentity = `-- name: CreateOAuthIdentity :one



INSERT INTO oauth_identities (

    id,

    user_id,

    provider,

    provider_user_id,

    email

)

VALUES (

    $1,

    $2,

    $3,

    $4,

    $5

)

RETURNING id, user_id, provider, provider_user_id, email, created_at
`

type CreateOAuthIdentityParams struct {
	ID             uuid.UUID `json:"id"`
	UserID         uuid.UUID `json:"user_id"`
	Provider       string    `json:"provider"`
	ProviderUserID string    `json:"provider_user_id"`
	Email          string    `json:"email"`
}

// =====================================================
// Create OAuth Identity
//
// Links a third-party identity to an account. The unique
// constraint on (provider, provider_user_id) is the real
// guarantee — this insert failing on conflict means the
// identity is already linked, which the caller should
// never hit given the FindByProviderID check that always
// precedes it (see docs/oauth.md).
// =====================================================
func (q *Queries) CreateOAuthIdentity(ctx context.Context, arg CreateOAuthIdentityParams) (OauthIdentity, error) {
	row := q.db.QueryRow(ctx, createOAuthIdentity,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.Email,
	)
	var i OauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthIdentityByProviderID = `-- name: GetOAuthIdentityByProviderID :one



SELECT id, user_id, provider, provider_user_id, email, created_at

FROM oauth_identities

WHERE provider = $1

AND provider_user_id = $2
`

type GetOAuthIdentityByProviderIDParams struct {
	Provider       string `json:"provider"`
	ProviderUserID string `json:"provider_user_id"`
}

// =====================================================
// Find OAuth Identity By Provider
//
// The lookup that decides which of the three account-linking
// cases applies (docs/adr/0001-oauth-client-and-account-linking.md):
// a row here means a returning user, no row means either a
// brand-new account or an email collision to resolve.
// =====================================================
func (q *Queries) GetOAuthIdentityByProviderID(ctx context.Context, arg GetOAuthIdentityByProviderIDParams) (OauthIdentity, error) {
	row := q.db.QueryRow(ctx, getOAuthIdentityByProviderID, arg.Provider, arg.ProviderUserID)
	var i OauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}
