// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one

INSERT INTO sessions
(
    id,
    user_id,
    device_id,
    device_name,
    device_type,
    user_agent,
    ip_address
)
VALUES
(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, user_id, device_id, device_name, device_type, user_agent, ip_address, last_used_at, revoked_at, created_at, updated_at
`

type CreateSessionParams struct {
	ID         uuid.UUID  `json:"id"`
	UserID     uuid.UUID  `json:"user_id"`
	DeviceID   string     `json:"device_id"`
	DeviceName string     `json:"device_name"`
	DeviceType DeviceType `json:"device_type"`
	UserAgent  string     `json:"user_agent"`
	IpAddress  string     `json:"ip_address"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.DeviceID,
		arg.DeviceName,
		arg.DeviceType,
		arg.UserAgent,
		arg.IpAddress,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.DeviceName,
		&i.DeviceType,
		&i.UserAgent,
		&i.IpAddress,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec

UPDATE sessions
SET revoked_at = NOW()
WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}
