// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeVerificationToken = `-- name: ConsumeVerificationToken :execrows



UPDATE email_verification_tokens

SET consumed_at = NOW()

WHERE id = $1

AND consumed_at IS NULL
`

// =====================================================
// Consume Token
//
// Atomic operation. Prevents double verification.
// =====================================================
func (q *Queries) ConsumeVerificationToken(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, consumeVerificationToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createVerificationToken = `-- name: CreateVerificationToken :one



INSERT INTO email_verification_tokens (

    id,

    user_id,

    token_hash,

    expires_at

)

VALUES (

    $1,

    $2,

    $3,

    $4

)

RETURNING id, user_id, token_hash, expires_at, consumed_at, created_at
`

type CreateVerificationTokenParams struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// =====================================================
// Create Verification Token
// =====================================================
func (q *Queries) CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, createVerificationToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveVerificationTokenByUserID = `-- name: GetActiveVerificationTokenByUserID :one



SELECT id, user_id, token_hash, expires_at, consumed_at, created_at

FROM email_verification_tokens

WHERE user_id = $1

AND consumed_at IS NULL

AND expires_at > NOW()

ORDER BY created_at DESC

LIMIT 1
`

// =====================================================
// Find Active Token For User
//
// "Active" means unconsumed and unexpired. Used by resend to decide
// whether to reuse the existing token instead of minting a new one.
// =====================================================
func (q *Queries) GetActiveVerificationTokenByUserID(ctx context.Context, userID uuid.UUID) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getActiveVerificationTokenByUserID, userID)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getVerificationTokenByHash = `-- name: GetVerificationTokenByHash :one



SELECT id, user_id, token_hash, expires_at, consumed_at, created_at

FROM email_verification_tokens

WHERE token_hash = $1
`

// =====================================================
// Find Token By Hash
// =====================================================
func (q *Queries) GetVerificationTokenByHash(ctx context.Context, tokenHash string) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getVerificationTokenByHash, tokenHash)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}
